# Generated by Django 4.1.4 on 2023-02-02 14:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='A_brief_Discription',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
