# Generated by Django 4.1.4 on 2023-02-02 14:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_alter_post_a_brief_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Help',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
