# Generated by Django 4.1.4 on 2023-02-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0009_alter_comment_user_alter_post_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Academic_Cart',
        ),
        migrations.DeleteModel(
            name='Digital_Cart',
        ),
        migrations.DeleteModel(
            name='Fashion_Cart',
        ),
        migrations.DeleteModel(
            name='Interior_Cart',
        ),
        migrations.DeleteModel(
            name='Medical_Cart',
        ),
        migrations.DeleteModel(
            name='Self_Care_Cart',
        ),
        migrations.DeleteModel(
            name='Talent_Cart',
        ),
        migrations.DeleteModel(
            name='Travel_Cart',
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='title', max_length=200),
        ),
    ]
